LabsWebApp3/Models/Domain/Entities/EventItem.cs
using System.ComponentModel.DataAnnotations;

namespace LabsWebApp3.Models.Domain.Entities
{
    public class EventItem : EntityBase
    {
        [Required(ErrorMessage = "Заполните название события")]
        [Display(Name = "Название события")]
        public override string Title { get; set; }
        [Display(Name = "Краткое описание события")]
        public override string Subtitle { get; set; }

        [Display(Name = "Полное описание события")]
        public override string Text { get; set; }
    }
}

LabsWebApp3/Areas/Admin/Controllers/EventItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using LabsWebApp3.Models.Domain;
using LabsWebApp3.Models.Domain.Entities;
using LabsWebApp3.Helpers;

namespace LabsWebApp3.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EventItemsController : Controller
    {
        private readonly DataManager dataManager;
        public EventItemsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new EventItem() 
                : dataManager.EventItems.GetItemById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(EventItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    string saveName = titleImageFile.ToSaveFileName(out bool mustSave);

                    if (mustSave && saveName.Equals(string.Empty))
                    {
                        ModelState.AddModelError("SaveImgError", $"В базе картинок существует другой файл с именем: \"{titleImageFile.FileName}\"," +
                            $" переименуйте исходный файл при дальнейшем редактирование  \"{model.Title}\", или нажмите \"Сохранить\" (без сохранения/изменения картинки).");
                        return View(model);
                    }
                    model.TitleImagePath = titleImageFile.FileName;
                    if (mustSave)
                    {
                        using var stream = new FileStream(saveName, FileMode.Create);
                        titleImageFile.CopyTo(stream);
                    }
                }
                AutoSEO.Set(model);
                dataManager.EventItems.SaveItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        public IActionResult Delete(Guid id)
        {
            dataManager.EventItems.DeleteItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

LabsWebApp3/Areas/Admin/Views/EventItems/Edit.cshtml
@model EventItem
@{
    string strTitle = Model.Id == default 
        ? "Добавить новое событие" 
        : "Редактировать событие";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="EventItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TitleImagePath" />
            
            @if(!ViewData.ModelState.IsValid)
            {
                <div class="warning-text" asp-validation-summary="All"></div>
            }
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span class="warning-text" asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="DateAdded"></label>
                <input type="datetime-local" asp-for="DateAdded" />
                <span class="warning-text" asp-validation-for="DateAdded"></span>
                <label>(Если установлено время "00:00", то Событие без времени, только дата. Для установки времени "00:00" - "00:01".)</label>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span class="warning-text" asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span class="warning-text" asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                @if (!string.IsNullOrWhiteSpace(Model.TitleImagePath))
                {
                    <div>
                        <img class="img-block" src="~/images/DB/@Model.TitleImagePath" />
                    </div>
                }
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span class="warning-text" asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span class="warning-text" asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span class="warning-text" asp-validation-for="MetaKeywords"></span>
            </div>
            @if (!ViewData.ModelState.IsValid && ViewData.ModelState["SaveImgError"]?.Errors.Count > 0)
            {
                <div class="alert" role="alert">
                    <div class="div-color-red">
                        <strong>Не удалось сохранить из-за титульной картинки!</strong><br />
                        @ViewData.ModelState["SaveImgError"].Errors.First().ErrorMessage
                    </div>
                </div>
            }
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

<script type="text/javascript">
    @if (!ViewData.ModelState.IsValid && ViewData.ModelState["SaveImgError"]?.Errors.Count > 0)
        {
            <text>
            $(document).ready(function() {
                alert('@ViewData.ModelState["SaveImgError"].Errors.First().ErrorMessage');
            });
            </text>
        }
</script>